### ISSUE TITLE
Run import pipeline perodically

### ISSUE THREAD

**Issue by lukas-rotsching** [amosproj/amos2023ss02-open-search-meta-data-hub#102]
## User story

1. As a user
2. I want the import pipeline to run periodically
3. So that always have reasonably up-to-date clone of the MdH

## Acceptance criteria

* Schedule the import pipeline to run automatically in regular intervals (e.g. via cron)

## Definition of done (DoD)

A feature is considered complete when

* All of its acceptance criteria have been met.
* It has been thoroughly tested.
* The code has been peer reviewed by the dedicated team.
* It can be seamlessly integrated into the main branch without causing any negative side effects.
* Its core functionality has been thoroughly documented.

## DoD general criteria

* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by JMiltner97** [comment]
FROM python:3.8-slim

# Install cron
RUN apt-get update && apt-get -y install cron

# Copy Python dependencies
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# Copy Python script
COPY my_script.py /my_script.py

# Copy cron job file to the cron.d directory
COPY my_cron /etc/cron.d/my_cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/my_cron

# Apply cron job
RUN crontab /etc/cron.d/my_cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
