### ISSUE TITLE
Configfile: import pipeline filters

### ISSUE THREAD

**Issue by lukas-rotsching** [amosproj/amos2023ss02-open-search-meta-data-hub#109]
## User story

1. As a user
2. I need more options to control the import pipeline via the config file
3. So that i have finer control over what data are imported into my OS node

## Acceptance criteria

* Add an option to control the file types that are imported.
* (optional )Add an option to only import files newer than a certain timestamp.
* (optional) Add an option to only import files which names match a given pattern.
* Make all the above options default to 'all'/'no restrictions'

## Definition of done (DoD)

A feature is considered complete when

* All of its acceptance criteria have been met.
* It has been thoroughly tested.
* The code has been peer reviewed by the dedicated team.
* It can be seamlessly integrated into the main branch without causing any negative side effects.
* Its core functionality has been thoroughly documented.

## DoD general criteria

* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by motrell** [comment]
The required points are almost implemented and will be pretty sure ready to the end of the current sprint.
