### ISSUE TITLE
Create doodle for team meeting before demo day

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2023ss02-open-search-meta-data-hub#125]
**Priority (1-3)**: 3

## Description ##
- Next week is the demo day. We are required to have one last team meeting before the demo day to conclude the last sprint.

## Required Action ##
- Create a doodle to find a suitable meeting slot for a mandatory team meeting before the demo day.

**Comment by motrell** [comment]
you can now vote, link is on discord.

Btw, use terminklick.stuve.fau.de for things like that, because it's from some other students :)
