### ISSUE TITLE
Research Dashboard Statistics

### ISSUE THREAD

**Issue by lukas-rotsching** [amosproj/amos2023ss02-open-search-meta-data-hub#16]
## User story
1. As a user
2. I need visually pleasing, detailed statistics in my dashboard
3. So that i have an overview of the data i have indexed

## Acceptance criteria
* Research how to display graphs and charts in the dashboard
* Research if OpenSearch offers an easy way to create charts and graphs about statistics of the indexed data
* Take a look at the statistics dashboard of our MdH Core and evaluate which features of this dashboard we can also implement for the OpenSearch dashboard
* Research if there is an easy way to 'export' the graphs from the OS-Dashboard to our search page #26 
* Write a short summary of your research with useful links, resources, code examples... that you may find while researching

## Definition of done (DoD)
A feature is considered complete when
  * All of its acceptance criteria have been met.
  * It has been thoroughly tested.
  * The code has been peer reviewed by the dedicated team.
  * It can be seamlessly integrated into the main branch without causing any negative side effects.
  * Its core functionality has been thoroughly documented.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by leondaniel22** [comment]
Amir and me created a PowerPoint presentation that contains various information about OpenSearch, OpenSearch Dashboard and addtional information.
