### ISSUE TITLE
Simple website

### ISSUE THREAD

**Issue by tawfeeka** [amosproj/amos2023ss02-open-search-meta-data-hub#26]
## User story
1. As a user, 
2. I would like to simplify the process of configuring my OpenSearch search queries
3. By having access to a user-friendly website, which allows me to easily customize the searches that are important to me.

## Acceptance criteria
* The website is accessible.
* The website is integrated in Docker.

## Definition of done (DoD)
A feature is considered complete when
  * All of its acceptance criteria have been met.
  * It has been thoroughly tested.
  * The code has been peer reviewed by the dedicated team.
  * It can be seamlessly integrated into the main branch without causing any negative side effects.
  * Its core functionality has been thoroughly documented.

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by leondaniel22** [comment]
This ticket will be not completely done for the upcoming sprint. We have a Website so far but it has not functionality.
