### ISSUE TITLE
Use pings in Discord more frequently

### ISSUE THREAD

**Issue by i315315** [amosproj/amos2023ss02-open-search-meta-data-hub#7]
**Priority (1-3)**: 3

## Description ##

- In our Discord, it is not possible to address certain roles in the team directly. Therefore, some messages don't get answers fast enough.

## Required Action ##

In Discord, roles for certain team members (everyone, POs, SDs, SM) will be implemented that allow for direct addressing of these roles.

**Comment by motrell** [comment]
@i315315 just to make it look nice: The issue-title should mean Discord, not GitHub, right? 😅

**Comment by i315315** [comment]
@motrell Yes, absolutely :-D My bad, sorry. I corrected it.

**Comment by motrell** [comment]
Updated Discord and added a Discord-Policy. Waiting for feedback.
