### ISSUE TITLE
Search Tag Boosting

### ISSUE THREAD

**Issue by lukas-rotsching** [amosproj/amos2023ss02-open-search-meta-data-hub#76]
## User story

1. As a user
2. I need a way to prioritize search criteria in an advanced search
3. So that i have better control over what i am searching for

## Acceptance criteria

* OpenSearch seemingly comes with a feature to 'boost' tags in a search query. Research how this feature can be used (is it just a flag boost=true/false or can it also specify bost 'weights' )
* Add an option to utilize the boost feature (e.g. additional input boxes where i can input the 'boost weight' for a search criteria. but pls don't force me to input a value into every box)

## Definition of done (DoD)

A feature is considered complete when

* All of its acceptance criteria have been met.
* It has been thoroughly tested.
* The code has been peer reviewed by the dedicated team.
* It can be seamlessly integrated into the main branch without causing any negative side effects.
* Its core functionality has been thoroughly documented.

## DoD general criteria

* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by JMiltner97** [comment]
Frontend implementation is done. If backend is functional this ticket can be tested
