### ISSUE TITLE
Design Overhaul

### ISSUE THREAD

**Issue by lukas-rotsching** [amosproj/amos2023ss02-open-search-meta-data-hub#79]
## User story

1. As a user
2. I need a good looking and functional frontend
3. So that i can use the functionality provided by the backend

## Acceptance criteria

* The frontend seemingly has some issues (switching back to to simple search when submit button is pressed in advanced search while certain operators are selected, showing only 10 results...). Fix those
* Polish the design of the front end
* Test the front end with different browsers, on different operating systems and with different screen resolutions and fix problems.

## Definition of done (DoD)

A feature is considered complete when

* All of its acceptance criteria have been met.
* It has been thoroughly tested.
* The code has been peer reviewed by the dedicated team.
* It can be seamlessly integrated into the main branch without causing any negative side effects.
* Its core functionality has been thoroughly documented.

## DoD general criteria

* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by motrell** [comment]
Now, we know how to change the limit setting to e.g. 1,000,000 results. This is not a perfect solution, but better than nothing. Maybe we can improve this in future.

**Comment by motrell** [comment]
We tested our website on three different browsers (Chrome, Firefox, Edge) and it looks good.
