### ISSUE TITLE
fuzzy find tags

### ISSUE THREAD

**Issue by tawfeeka** [amosproj/amos2023ss02-open-search-meta-data-hub#89]
## User story

1. As a user,
2. I want to leverage the power of fuzzy find,
3. So that I can easily search for and find relevant information even with partial or misspelled inputs.

## Acceptance criteria

* Take inspiration from the [fzf](https://github.com/junegunn/fzf) program.
* Test as extensively as possible.

## Definition of done (DoD)

A feature is considered complete when

* All of its acceptance criteria have been met.
* It has been thoroughly tested.
* The code has been peer reviewed by the dedicated team.
* It can be seamlessly integrated into the main branch without causing any negative side effects.
* Its core functionality has been thoroughly documented.

## DoD general criteria

* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by JMiltner97** [comment]
This functionality has been implemented in the fuzzy-find branch. Please feel to test it, so awe can proceed with the merge into main lateron
