### ISSUE TITLE
Tags limitation

### ISSUE THREAD

**Issue by tawfeeka** [amosproj/amos2023ss02-open-search-meta-data-hub#99]
## User story

1. As a user, 
2. I would like to have the ability to set the limitation of the number of imported tags in the config file 
3. So that I can control it.

## Acceptance criteria

* The config file should provide a meaningful key where the user can set the number of imported tags.
* The documentation should include a corresponding example that allows users to easily apply it.

## Definition of done (DoD)

A feature is considered complete when

* All of its acceptance criteria have been met.
* It has been thoroughly tested.
* The code has been peer reviewed by the dedicated team.
* It can be seamlessly integrated into the main branch without causing any negative side effects.
* Its core functionality has been thoroughly documented.

## DoD general criteria

* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by lukas-rotsching** [comment]
duplicate #98
